DROP DATABASE IF EXISTS products;
CREATE DATABASE products;

USE products;

DROP TABLE IF EXISTS product;

DROP TABLE IF EXISTS product;
CREATE TABLE product(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NULL,
  subTitle VARCHAR(255) NULL,
  description VARCHAR(255) NULL,
  specialty VARCHAR(255) NULL,
  price INT NULL
);

DROP TABLE IF EXISTS details;
CREATE TABLE details(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  goodToKnow VARCHAR(255) NULL,
  icons VARCHAR(255) NULL,
  shades VARCHAR(255) NULL,
  keywords VARCHAR(255) NULL
);

DROP TABLE IF EXISTS images;
CREATE TABLE images(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  image VARCHAR(255) NOT NULL
);