DROP DATABASE IF EXISTS products;
CREATE DATABASE products;

USE products;

CREATE TABLE product(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NULL,
  subTitle VARCHAR(255) NULL,
  description VARCHAR(255) NULL,
  specialty VARCHAR(255) NULL,
  price INT NULL,
  ingredients VARCHAR(1000) NULL,
  howTo VARCHAR(255) NULL
);

CREATE TABLE details(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  goodToKnow VARCHAR(255) NULL,
  icons VARCHAR(255) NULL,
  shades VARCHAR(255) NULL,
  keywords VARCHAR(255) NULL
);

CREATE TABLE images(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  image VARCHAR(255) NOT NULL
);